services:
  redis_cache:
    image: redis:latest
    container_name: redisCache_api_gateway
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisInsight_api_gateway
    ports:
      - "5540:5540"
    restart: always

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: example
