apiVersion: apps/v1
kind: Deployment
metadata:
  name: answer-service-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: answer-service
  template:
    metadata:
      labels:
        app: answer-service
    spec:
      containers:
        - name: answer-service-container
          image: dinaasaur/answer-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: answer-service-config
                  key: DATABASE_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: answer-service-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: answer-service-db-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
                cpu: "500m"
                memory: "512Mi"
#            livenessProbe:
#              httpGet:
#                path: /health
#                port: 8080
#              initialDelaySeconds: 30
#              periodSeconds: 10
#            readinessProbe:
#              httpGet:
#                path: /ready
#                port: 8080
#              initialDelaySeconds: 5
#              periodSeconds: 10

