services:
  #  app:
  #    build: .
  #    ports:
  #      - "8083:8083"
  #    depends_on:
  #      - mongodb
  #    environment:
  #      - SPRING_APPLICATION_NAME=answer-service
  #      - SPRING_DATA_MONGODB_URI=mongodb://mongo:secret@mongodb:27017/miniappdb?authSource=admin

  mongodb:
    image: mongo
    container_name: mongo_answer
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: miniappdb
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodata:/data/db

#  rabbitmq:
#    image: rabbitmq:4.0-management
#    ports:
#      - "5676:5672"
#      - "15676:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: root
#      RABBITMQ_DEFAULT_PASS: example
#
#  redis_cache:
#    image: redis:latest
#    container_name: redisCache_answer
#    ports:
#      - "6382:6379"

#  mongo-express:
#    image: mongo-express
#    container_name: miniapp-mongo-express
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
#      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
#      ME_CONFIG_MONGODB_SERVER: mongodb
#    depends_on:
#      - mongodb

#  redisinsight:
#    image: redis/redisinsight:latest
#    container_name: redisInsight_answer
#    ports:
#      - "5540:5540"
#    restart: always

volumes:
  pgdata:
  mongodata:
