apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-answer
spec:
  serviceName: "mongo-answer"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-answer
  template:
    metadata:
      labels:
        app: mongo-answer
    spec:
      containers:
        - name: mongo-answer
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret-answer
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret-answer
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: mongo-persistent-volume
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
