apiVersion: v1
kind: Service
metadata:
  name: mongo-answer
  labels:
    app: mongo-answer
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None # Headless service
  selector:
    app: mongo-answer
