services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_URL:jdbc:postgresql://postgres:5432/appdb
      - POSTGRES_DB=appdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"

#  rabbitmq:
#    image: rabbitmq:4.0-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: root
#      RABBITMQ_DEFAULT_PASS: example