spring:
    application:
        name: answer-service

data:
    mongodb:
        uri: ${MONGODB_URL:mongodb://root:example@localhost:27017/appdb?authSource=admin}
    redis:
        host: redis
        port: 6379
        password: example

    rabbitmq:
        host: rabbitmq
        port: 5672
        username: root
        password: example

server:
    port: 8085