spring:
    application:
        name: answer-service

    data:
        mongodb:
            uri: mongodb://mongo:secret@mongodb:27017/miniappdb?authSource=admin
        redis:
            host: redis
            port: 6379
            password: example

        rabbitmq:
            host: rabbitmq
            port: 5672
            username: root
            password: example

server:
    port: 8085