spring:
  application:
    name: answer-service

  data:
    mongodb:
      uri: mongodb://mongo:secret@localhost:27018/miniappdb?authSource=admin
    #            uri: mongodb+srv://seifsabra2002:secretPass@account-service.anxb0r2.mongodb.net/answerService
      database: answer_db
    redis:
      host: localhost
      port: 6382

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: example

server:
  port: 8083
