apiVersion: apps/v1
kind: Deployment
metadata:
  name: answer-service
  namespace: qa-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: answer-service
  template:
    metadata:
      labels:
        app: answer-service
    spec:
      containers:
        - name: answer-service
          image: seiffhany/answer-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/qa_platform"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: answer-service
  namespace: qa-platform
spec:
  selector:
    app: answer-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
