version: "3.8"

services:
  # notification-service:
  #   build: .
  #   container_name: notification-service
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - MONGODB_URL=mongodb://root:example@mongo:27017/appdb?authSource=admin
  #     - SPRING_DATA_REDIS_HOST=redis
  #     - SPRING_DATA_REDIS_PORT=6379
  #     - SPRING_DATA_REDIS_PASSWORD=example
  #     - SPRING_RABBITMQ_HOST=rabbitmq
  #     - SPRING_RABBITMQ_PORT=5672
  #     - SPRING_RABBITMQ_USERNAME=root
  #     - SPRING_RABBITMQ_PASSWORD=example
  #   depends_on:
  #     - mongo
  #     - redis
  #     - rabbitmq

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: appdb
    ports:
      - "27017:27017"

#    volumes:
#      - mongo_data:/data/db

#    volumes:
#      - redis_data:/data
#      - rabbitmq_data:/var/lib/rabbitmq
#
#volumes:
#  mongo_data:
#  redis_data:
#  rabbitmq_data:
