services:
  #  user-service:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    container_name: user-service
  #    ports:
  #      - "8080:8080"
  #    environment:
  #      - POSTGRES_URL=jdbc:postgresql://postgres:5432/appdb
  #      - POSTGRES_USER=postgres
  #      - POSTGRES_PASSWORD=password
  #      - REDIS_HOST=redis
  #      - REDIS_PORT=6379
  #      - REDIS_PASSWORD=password
  #      - SPRING_PROFILES_ACTIVE=prod
  #    depends_on:
  #      postgres:
  #        condition: service_healthy
  #      redis:
  #        condition: service_healthy

  postgres:
    image: postgres
    container_name: postgres_user
    environment:
      - POSTGRES_DB=usersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
#
#  redis_cache:
#    image: redis:latest
#    container_name: redisCache_user
#    ports:
#      - "6381:6379"
#
#  redisinsight:
#    image: redis/redisinsight:latest
#    container_name: redisInsight_user
#    ports:
#      - "5541:5540"
#    restart: always
#
#  rabbitmq:
#    image: rabbitmq:4.0-management
#    container_name: rabbitmq_user
#    ports:
#      - "5675:5672"
#      - "15675:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: root
#      RABBITMQ_DEFAULT_PASS: example
