apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: qa-platform
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: question-service
  namespace: qa-platform
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  selector:
    app: question-service
---
apiVersion: v1
kind: Service
metadata:
  name: answer-service
  namespace: qa-platform
spec:
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  selector:
    app: answer-service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: qa-platform
spec:
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  selector:
    app: notification-service
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: qa-platform
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: api-gateway
