apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
  namespace: qa-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
        - name: question-service
          image: seiffhany/question-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/appdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "example"
---
apiVersion: v1
kind: Service
metadata:
  name: question-service
  namespace: qa-platform
spec:
  selector:
    app: question-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP
